[workspace]
members = [ "closure", "data_structure", "error_handling", "hash_table",
  "httpie"
, "lifetime", "memory", "multi_owner", "queryer", "smart_pointers", "sys_traits", "thumbor", "traits", "type_system"]

resolver = "2"
